#!/usr/bin/env node
/**
 * Generate or patch backend/.env for local development.
 *
 * Usage (from backend/):
 *   node scripts/generate-env.mjs
 *   node scripts/generate-env.mjs --force   # overwrite entire file
 *
 * Or: bun run generate-env
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const backendRoot = path.resolve(__dirname, '..');
const envPath = path.join(backendRoot, '.env');
const force = process.argv.includes('--force');

function randomHex(bytes = 64) {
    return crypto.randomBytes(bytes).toString('hex');
}

function parseEnvFile(content) {
    const out = {};
    for (const line of content.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        const key = trimmed.slice(0, eq).trim();
        let val = trimmed.slice(eq + 1).trim();
        if (
            (val.startsWith('"') && val.endsWith('"')) ||
            (val.startsWith("'") && val.endsWith("'"))
        ) {
            val = val.slice(1, -1);
        }
        out[key] = val;
    }
    return out;
}

function serializeEnv(vars, header) {
    const lines = [header, ''];
    const order = [
        'NODE_ENV',
        'PORT',
        'JWT_SECRET',
        'DB_HOST',
        'DB_PORT',
        'DB_NAME',
        'DB_USER',
        'DB_PASSWORD',
        'DB_SSL',
        'UPLOAD_DIR',
        'SHARE_ZIPS_DIR',
        'APP_URL',
        'FRONTEND_URL',
        'ORIGIN',
        'RP_ID',
        'ALLOWED_ORIGINS',
        'APP_LOCALE',
        'TZ',
        'CLAMAV_HOST',
        'CLAMAV_PORT',
        'DEMO_MODE',
    ];
    const written = new Set();
    for (const key of order) {
        if (vars[key] !== undefined && vars[key] !== '') {
            lines.push(`${key}=${vars[key]}`);
            written.add(key);
        }
    }
    for (const key of Object.keys(vars).sort()) {
        if (!written.has(key)) lines.push(`${key}=${vars[key]}`);
    }
    lines.push('');
    return lines.join('\n');
}

const header = `# Generated by backend/scripts/generate-env.mjs — do not commit (see .gitignore)
# Regenerate: cd backend && bun run generate-env`;

const defaults = {
    NODE_ENV: 'development',
    PORT: '3001',
    DB_HOST: 'localhost',
    DB_PORT: '5432',
    DB_NAME: 'nexoshare',
    DB_USER: 'postgres',
    DB_PASSWORD: 'postgres',
    DB_SSL: 'false',
    UPLOAD_DIR: './uploads',
    APP_URL: 'http://localhost:5173',
    FRONTEND_URL: 'http://localhost:5173',
    ORIGIN: 'http://localhost:5173',
    ALLOWED_ORIGINS: 'http://localhost:5173,http://localhost:3000',
    APP_LOCALE: 'en-GB',
    TZ: 'UTC',
    CLAMAV_HOST: 'localhost',
    CLAMAV_PORT: '3310',
    DEMO_MODE: 'false',
};

let existing = {};
if (fs.existsSync(envPath) && !force) {
    existing = parseEnvFile(fs.readFileSync(envPath, 'utf8'));
}

const merged = { ...defaults, ...existing };

const needsJwt =
    !merged.JWT_SECRET ||
    merged.JWT_SECRET === 'dev-secret-change-me' ||
    merged.JWT_SECRET === 'CHANGE_THIS_SECRET';

if (needsJwt || force) {
    merged.JWT_SECRET = randomHex(64);
}

if (!merged.DB_PASSWORD || merged.DB_PASSWORD === 'CHANGE_THIS_PASSWORD') {
    merged.DB_PASSWORD = randomHex(16);
}

if (force) {
    Object.assign(merged, defaults, { JWT_SECRET: merged.JWT_SECRET, DB_PASSWORD: merged.DB_PASSWORD });
}

fs.writeFileSync(envPath, serializeEnv(merged, header), 'utf8');

console.log(`✅ Wrote ${envPath}`);
if (needsJwt) {
    console.log('   • JWT_SECRET was generated (required to start the server).');
}
if (!existing.DB_PASSWORD && !force) {
    console.log('   • DB_PASSWORD was set — match this in your PostgreSQL user/database.');
}
console.log('\nNext steps:');
console.log('  1. Ensure PostgreSQL is running with DB_NAME/DB_USER/DB_PASSWORD from .env');
console.log('  2. cd backend && bun run dev');
console.log('  3. cd frontend && bun run dev  (Vite proxies /api to the backend)');
